### ISSUE TITLE
Ejercicio de AR con Objeto 3D

### ISSUE THREAD

**Issue by AxayacatlS** [SistemasTecTlaxiaco/realidad-aumentada-objeto-3d-equipo-axayacatl#2]
[Ejercicio de Realidad Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/realidad-aumentada-objeto-3d-equipo-axayacatl/files/6184388/Ejercicio.de.Realidad.Aumentada.pdf)

**Comment by ObedG** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
esta bien hecho..y revisado.
